### ISSUE TITLE
Add intersphinx linking for Ax and BoTorch 

### ISSUE THREAD

**Issue by jemissik** [madeline-scyphers/boa#37]
For more info on when ax and botroch can be linked:
see https://github.com/facebook/Ax/issues/1227
and see https://github.com/pytorch/botorch/issues/1464

**Comment by madeline-scyphers** [comment]
Can't do this without Ax and BoTorch support (they use sphinx to build their docs, but then cannibalize the sphinx HTML pages without taking the objects.inv file and breaking the intersphinx stuff with it). Without Ax and BoTorch buy in, this is dead in the water. There is visibility for them now, maybe someday they will do it. Closing this since we can't do it until then.
